In [26]:
# Pandas Tutorial
import pandas as pd
dic = {
    "cutomers" : ["Anees", "Muhammad", "Rehman"],
    "Age" : [27, 45, 23],
    "city" : ["chakwal", "Lahore", "Islamabad"]
}
frame= pd.DataFrame(dic)
print(frame)

   cutomers  Age       city
0     Anees   27    chakwal
1  Muhammad   45     Lahore
2    Rehman   23  Islamabad

In [27]:
frame

   cutomers  Age       city
0     Anees   27    chakwal
1  Muhammad   45     Lahore
2    Rehman   23  Islamabad

In [28]:
sp = pd.Series([34, 23, 25], index = ["ali", "umer", "0098"])
print(sp)
print(sp["umer"])

# creating data Frames from the lists of the lists
dp = pd.DataFrame([["anees", 56],["umer", 34], ["ali", 35]], columns= ["name", "Score"])
dp

# creating dataFrames from the np Arrays

import numpy as np
array = np.array([[1,2],[4,5]])
sd = pd.DataFrame(array,columns = ["One", "two"])
sd

ali     34
umer    23
0098    25
dtype: int64
23

   One  two
0    1    2
1    4    5

In [35]:
data = pd.read_csv("raw_data.csv")
data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [51]:
data.head()
data.tail(3)
data.sample()
data.info()
data.shape
data.describe()
data.columns
data.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64

In [54]:
keg = pd.read_csv("globalAirQuality.csv")

In [74]:
# Selecting data
# 1. select columns 
keg["city"]
keg[["city","aqi"]]

# select rows, we used iloc and loc for accesing rows data, iloc for accessing with index and loc for accessing with labels

keg.loc[0:4]  # in loc the final values of label is also print

keg.iloc[0:4] # but with iloc the final values of the index is not included 

# select rows and colomns

keg.loc[0:4, ["city", "pm10", "co", "temperature"]]
keg.iloc[0:5,2:5]

# select single scaler value at and iat

keg.at[19, "city"]
keg.iat[10, 6]

# its a good practice to create a copy of the data when your are traying to change something because here it will create a view, in which
# if we change anything it will change the values in the original dataset

cities= keg["city"].copy()
cities[0] = "lahore"
print(cities)

0          lahore
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [75]:
keg

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [82]:
# Filtering of data
keg[keg["aqi"] < 30]
keg[(keg["aqi"] < 30) & (keg["temperature"] <30)]

keg[keg["aqi"] < 30][["city", "country"]]

# Query Based Filtering:

keg.query("aqi>200")

var = 100
keg.query("pm25 > @var")  # @ is used to reference the python variables in the query

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
745,2025-11-05 19:25:17.554219,GB,London,51.507,-0.128,107.144,43.819,13.389,4.601,21.680,0.890,214,19.055,66.245,1.637
8941,2025-11-17 07:25:17.554219,JP,Osaka,34.694,135.502,102.142,95.204,41.688,7.806,28.951,0.753,204,15.277,76.131,4.586
14555,2025-11-11 05:25:17.554219,PH,Manila,14.600,120.984,103.023,66.678,43.284,2.167,48.250,0.849,206,11.027,63.522,7.635
17529,2025-11-15 03:25:17.554219,FI,Helsinki,60.170,24.938,115.683,81.714,54.764,6.687,39.552,0.685,231,25.795,87.839,6.705

In [104]:
# cleaning the data

# Handling the Missing values
empdata = pd.read_csv("raw_data.csv")
empdata.isnull()
empdata.isnull().sum()    # Return the number of the mising values in the columns
empdata.dropna()          # Drop all the rows which contain the missing values and only shows rows which contain all the values
empdata.dropna(axis=1)    # Drop all the columns which contain any missing values

clean_data = empdata.copy()
age_mean = clean_data["age"].mean()
clean_data["age"] = clean_data["age"].fillna(age_mean)
clean_data

empdata.ffill()  # Forward Fill
empdata.bfill()  # Backward Fill


# Handling the Duplicates

empdata["country"].duplicated()
empdata.drop_duplicates()
clean_data.drop_duplicates(inplace=True)   # inplace is used to directly make the changes in the original data set


clean_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [115]:
empdata

# Handling Data types
empdata.dtypes
data_cop = empdata.copy()
data_cop["age"] = data_cop["age"].fillna(0)
data_cop["age"] = data_cop["age"].astype("int64")  # convert the one data type to another
data_cop.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [123]:

# Handling string values
empdata["name"].str.lower()
empdata["name"].str.upper()
empdata["name"].str.capitalize()
empdata["name"].str.split(" ")
empdata["name"].str.contains("lee", case = False)

0     False
1     False
2     False
3     False
4     False
5     False
6       NaN
7     False
8      True
9     False
10    False
Name: name, dtype: object

In [209]:

                # Transforming data (Feature Engineering)

#1-apply() to add a new feature column in the data with some logic
copy1 = empdata.copy()
copy1["tax"] = copy1["income"].apply(lambda x : "20%" if x < 55000 else"40%") # with lambda we directly write a function instead of
# writing it from the scratch. 
copy1

# 2-map() used to change the existing values to the new values
dic = { "Male" : "M", "Female" : "F", "Unknown" : "U"}
copy1["gender"] = copy1["gender"].map(dic)

# 3- assign() to assign new values in the new coloumn

copy1 = copy1.assign(new_income = copy1["income"] * 2)
copy1

# 4- replace(old, new) replace old values to the new ones

copy1["countr"] = copy1["country"].replace("USA", "US")
copy1 

#5- rename(column = {old:new} to change the coloumns of the data
copy1.columns = ["ID", "NAME", "AGE", "COUNTRY", "GENDER", "INCOME", "TAX", "NEW_INCOME","SOmething"]
copy1 = copy1.rename(columns = {"INCOME" : "SALARY"}) # for changing the name of the coloumns
# copy1 = copy1.rename(index = {1: "First"})   # for changing the vlues in the rows
copy1

# 6- sort_values() to sort out the values

sorted_val = copy1.sort_values("SALARY")
sorted_val

#copy1.sort_values("SALARY", ascending= False) # for decending order

# 7- sort_index()  # sort values based on index while reset index is used to the reset the index but still maintain the old index
sorted_val.reset_index()
sorted_val.reset_index(drop=True) # to delete the old index 
# 8- ranking

sorted_val["Ranking"] = sorted_val["NEW_INCOME"].rank(ascending = True, method = "min")  # in rank 1 is the loweest value to make it opposite ascending = true is used
sorted_val  # method is used to resolve the ties you can do it max, min, dance > to get the mean value

,ID,NAME,AGE,COUNTRY,GENDER,SALARY,TAX,NEW_INCOME,SOmething,Ranking
9,9,Carlos Ruiz,NaN,Mexico,M,45000.0,20%,90000.0,Mexico,1.0
3,3,Alex,NaN,USA,U,47000.0,20%,94000.0,US,2.0
5,5,Li Wei,27.0,China,M,51000.0,20%,102000.0,China,3.0
0,1,John Doe,29.0,USA,M,55000.0,40%,110000.0,US,4.0
1,1,John Doe,29.0,USA,M,55000.0,40%,110000.0,US,4.0
10,10,Emily Davis,31.0,USA,NaN,58000.0,40%,116000.0,US,6.0
2,2,Jane Smith,NaN,Canada,F,62000.0,40%,124000.0,Canada,7.0
8,8,Rachel Lee,29.0,USA,F,62000.0,40%,124000.0,US,7.0
7,7,Ahmed Khan,38.0,NaN,M,68000.0,40%,136000.0,NaN,9.0
6,6,NaN,45.0,India,F,73000.0,40%,146000.0,India,10.0
4,4,Maria Garcia,34.0,Spain,F,NaN,40%,NaN,Spain,NaN

In [221]:
# task we need to shif the ID column to the end

copy2 = empdata.copy()
new_column = [ val for val in copy2.columns if val!= "id"] + ["id"]
print(new_column)
copy2[new_column]

# to store the data in jsv

copy3 = empdata.copy()
copy3 = copy3.drop_duplicates()
copy3 = copy3.fillna(0)
copy3 = copy3.sort_values("income")

copy3.to_csv("sorted_data.csv")

['name', 'age', 'country', 'gender', 'income', 'id']

In [233]:

# Grouping and Aggregation of data

copy4 = keg.copy()
copy4.groupby("city")["aqi"].mean()
copy4.groupby("city")["aqi"].agg(["mean", "min", "max"]) # this is called aggregation of data
copy4.groupby("city")["aqi"].aggregate(average = "mean", Minmun = "min", Maximum = "max")

                     average  Minmun  Maximum
city
Auckland          104.730556      47      225
Bangkok           105.191667      27      194
Beijing           104.411111      42      183
Bengaluru         102.333333      45      175
Berlin            104.422222      35      182
Buenos Aires      105.950000      44      197
Cairo             106.052778      42      190
Cape Town         106.158333      35      190
Chennai           103.627778      34      182
Chicago           104.805556      36      186
Delhi             106.441667      40      195
Doha              107.366667      45      187
Dubai             105.530556      43      189
Helsinki          105.108333      35      231
Ho Chi Minh City  101.536111      39      179
Hong Kong         103.488889      56      192
Houston           104.086111      38      187
Istanbul          104.083333      43      179
Jakarta           104.316667      48      198
Karachi           106.300000      48      186
Kolkata           103.525000      31      183
Kuala Lumpur      105.005556      32      194
Lagos             106.616667      44      190
London            103.044444      16      214
Los Angeles       104.477778      27      189
Madrid            105.488889      33      183
Manila            103.669444      32      206
Melbourne         102.444444      42      191
Mexico City       105.697222      40      196
Moscow            106.197222      48      197
Mumbai            105.397222      39      194
Nairobi           104.747222      46      172
New York          105.594444      43      192
Osaka             105.691667      38      204
Paris             105.763889      40      187
Riyadh            104.772222      29      182
Rome              105.033333      46      190
San Francisco     103.450000      26      187
Seoul             105.119444      43      183
Shanghai          101.375000      27      167
Singapore         106.480556      29      193
Stockholm         102.391667      42      196
Sydney            104.477778      36      193
São Paulo         104.319444      39      182
Tehran            102.150000      35      177
Tokyo             104.302778      33      183
Toronto           103.644444      42      176
Vancouver         105.444444      51      188
Warsaw            104.291667      31      197
Zurich            105.722222      38      203

In [264]:
# Melt and Pivot

#1- wide to long format

data = empdata.copy()
data.drop_duplicates()
melated_data = data.melt(
    id_vars = ["country", "name"],
    value_vars = ["age", "gender", "income"],
    var_name="Melted_data
    
    
melated_data

   country          name Melted_data New Values
0      USA      John Doe         age       29.0
1      USA      John Doe         age       29.0
2   Canada    Jane Smith         age        NaN
3      USA          Alex         age        NaN
4    Spain  Maria Garcia         age       34.0
5    China        Li Wei         age       27.0
6    India           NaN         age       45.0
7      NaN    Ahmed Khan         age       38.0
8      USA    Rachel Lee         age       29.0
9   Mexico   Carlos Ruiz         age        NaN
10     USA   Emily Davis         age       31.0
11     USA      John Doe      gender       Male
12     USA      John Doe      gender       Male
13  Canada    Jane Smith      gender     Female
14     USA          Alex      gender    Unknown
15   Spain  Maria Garcia      gender     Female
16   China        Li Wei      gender       Male
17   India           NaN      gender     Female
18     NaN    Ahmed Khan      gender       Male
19     USA    Rachel Lee      gender     Female
20  Mexico   Carlos Ruiz      gender       Male
21     USA   Emily Davis      gender        NaN
22     USA      John Doe      income    55000.0
23     USA      John Doe      income    55000.0
24  Canada    Jane Smith      income    62000.0
25     USA          Alex      income    47000.0
26   Spain  Maria Garcia      income        NaN
27   China        Li Wei      income    51000.0
28   India           NaN      income    73000.0
29     NaN    Ahmed Khan      income    68000.0
30     USA    Rachel Lee      income    62000.0
31  Mexico   Carlos Ruiz      income    45000.0
32     USA   Emily Davis      income    58000.0

In [263]:
#2. Pivot Function - to convert long data to wide data
# pivot() is used when we don't have duplicate data while the pivot_table is used to handle the duplicated data
original = melated_data.pivot_table(
    index= ["country", "name"],
    columns= ["Melted_data"],
    values= "New Values",
    aggfunc= "first").reset_index()  # moves the index back to columns and creates a new default integer index (0, 1, 2, …).
original

Melted_data country          name   age   gender   income
0            Canada    Jane Smith   NaN   Female  62000.0
1             China        Li Wei  27.0     Male  51000.0
2            Mexico   Carlos Ruiz   NaN     Male  45000.0
3             Spain  Maria Garcia  34.0   Female      NaN
4               USA          Alex   NaN  Unknown  47000.0
5               USA   Emily Davis  31.0      NaN  58000.0
6               USA      John Doe  29.0     Male  55000.0
7               USA    Rachel Lee  29.0   Female  62000.0