In [26]:
# Pandas Tutorial
import pandas as pd
dic = {
    "cutomers" : ["Anees", "Muhammad", "Rehman"],
    "Age" : [27, 45, 23],
    "city" : ["chakwal", "Lahore", "Islamabad"]
}
frame= pd.DataFrame(dic)
print(frame)

   cutomers  Age       city
0     Anees   27    chakwal
1  Muhammad   45     Lahore
2    Rehman   23  Islamabad

In [27]:
frame

   cutomers  Age       city
0     Anees   27    chakwal
1  Muhammad   45     Lahore
2    Rehman   23  Islamabad

In [28]:
sp = pd.Series([34, 23, 25], index = ["ali", "umer", "0098"])
print(sp)
print(sp["umer"])

# creating data Frames from the lists of the lists
dp = pd.DataFrame([["anees", 56],["umer", 34], ["ali", 35]], columns= ["name", "Score"])
dp

# creating dataFrames from the np Arrays

import numpy as np
array = np.array([[1,2],[4,5]])
sd = pd.DataFrame(array,columns = ["One", "two"])
sd

ali     34
umer    23
0098    25
dtype: int64
23

   One  two
0    1    2
1    4    5

In [35]:
data = pd.read_csv("raw_data.csv")
data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [51]:
data.head()
data.tail(3)
data.sample()
data.info()
data.shape
data.describe()
data.columns
data.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64

In [54]:
keg = pd.read_csv("globalAirQuality.csv")

In [74]:
# Selecting data
# 1. select columns 
keg["city"]
keg[["city","aqi"]]

# select rows, we used iloc and loc for accesing rows data, iloc for accessing with index and loc for accessing with labels

keg.loc[0:4]  # in loc the final values of label is also print

keg.iloc[0:4] # but with iloc the final values of the index is not included 

# select rows and colomns

keg.loc[0:4, ["city", "pm10", "co", "temperature"]]
keg.iloc[0:5,2:5]

# select single scaler value at and iat

keg.at[19, "city"]
keg.iat[10, 6]

# its a good practice to create a copy of the data when your are traying to change something because here it will create a view, in which
# if we change anything it will change the values in the original dataset

cities= keg["city"].copy()
cities[0] = "lahore"
print(cities)

0          lahore
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [75]:
keg

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [82]:
# Filtering of data
keg[keg["aqi"] < 30]
keg[(keg["aqi"] < 30) & (keg["temperature"] <30)]

keg[keg["aqi"] < 30][["city", "country"]]

# Query Based Filtering:

keg.query("aqi>200")

var = 100
keg.query("pm25 > @var")  # @ is used to reference the python variables in the query

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
745,2025-11-05 19:25:17.554219,GB,London,51.507,-0.128,107.144,43.819,13.389,4.601,21.680,0.890,214,19.055,66.245,1.637
8941,2025-11-17 07:25:17.554219,JP,Osaka,34.694,135.502,102.142,95.204,41.688,7.806,28.951,0.753,204,15.277,76.131,4.586
14555,2025-11-11 05:25:17.554219,PH,Manila,14.600,120.984,103.023,66.678,43.284,2.167,48.250,0.849,206,11.027,63.522,7.635
17529,2025-11-15 03:25:17.554219,FI,Helsinki,60.170,24.938,115.683,81.714,54.764,6.687,39.552,0.685,231,25.795,87.839,6.705

In [104]:
# Handling the Missing values
empdata = pd.read_csv("raw_data.csv")
empdata.isnull()
empdata.isnull().sum()    # Return the number of the mising values in the columns
empdata.dropna()          # Drop all the rows which contain the missing values and only shows rows which contain all the values
empdata.dropna(axis=1)    # Drop all the columns which contain any missing values

clean_data = empdata.copy()
age_mean = clean_data["age"].mean()
clean_data["age"] = clean_data["age"].fillna(age_mean)
clean_data

empdata.ffill()  # Forward Fill
empdata.bfill()  # Backward Fill


# Handling the Duplicates

empdata["country"].duplicated()
empdata.drop_duplicates()
clean_data.drop_duplicates(inplace=True)   # inplace is used to directly make the changes in the original data set


clean_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [115]:
empdata

empdata.dtypes
data_cop = empdata.copy()
data_cop["age"] = data_cop["age"].fillna(0)
data_cop["age"] = data_cop["age"].astype("int64")  # convert the one data type to another
data_cop.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [120]:
empdata["name"].str.lower()
empdata["name"].str.upper()
empdata["name"].str.capitalize()
empdata["name"].str.split(" ")

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object